development:
  aws:
    project:
      image_server:
        s3:
          bucket: 'image-upload-kyoppii'
          prefix:
            item: 'item'
  cdn:
    domain: http://dt9hdwu9txswj.cloudfront.net
